#!/usr/bin/env sh
set -eu

SCRIPT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
cd "$SCRIPT_DIR"

export POSTERR_JELLYFIN_LIBRARY_FIRST_PAGE_LIMIT="60"
export POSTERR_JELLYFIN_LIBRARY_FIRST_PAGE_FALLBACK_LIMIT="20"
export POSTERR_JELLYFIN_LIBRARY_FIRST_PAGE_TIMEOUT_MS="45000"
export POSTERR_JELLYFIN_LIBRARY_PAGE_LIMIT="150"
export POSTERR_SYNC_DEBUG="true"

echo "Starting PosterX from $SCRIPT_DIR ..."
node "./index.js"
